# Generated by Django 5.2.5 on 2025-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='location',
            field=models.CharField(default='Remote', max_length=100),
        ),
    ]
