import { type Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { Hero } from "@/components/Hero";
import { Stats } from "@/components/Stats";
import { FeaturedGigs } from "@/components/FeaturedGigs";
import { Testimonials } from "@/components/Testimonials";
import { GrowWithUs } from "@/components/GrowWithUs";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className}`}>
        <Hero />
        <Stats />
        <FeaturedGigs />
        <Testimonials />
        <GrowWithUs />
        {children}
      </body>
    </html>
  );
}
