# Generated by Django 5.2.6 on 2025-09-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the gig.', max_length=200)),
                ('description', models.TextField(help_text='A detailed description of the gig.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price for the gig.', max_digits=10)),
                ('location', models.CharField(help_text='The city or area where the gig is located.', max_length=100)),
                ('contact_email', models.EmailField(help_text='Email address for gig inquiries.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Optional phone number for contact.', max_length=20, null=True)),
                ('image', models.ImageField(help_text='An image representing the gig.', upload_to='gig_images/')),
                ('date', models.DateField(help_text='The date the gig will take place.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the gig was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the gig was last updated.')),
            ],
        ),
    ]
