# Generated by Django 5.2.6 on 2025-09-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clerkuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkuser',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
