# Generated by Django 5.2.6 on 2025-09-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clerkuser_is_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerkuser',
            name='is_freelancer',
        ),
        migrations.AddField(
            model_name='clerkuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clerkuser',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
