# Generated by Django 5.2.6 on 2025-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_clerkuser_is_freelancer_clerkuser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerkuser',
            name='id',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clerkuser',
            name='clerk_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
