# Generated by Django 5.2.6 on 2025-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_clerkuser_id_mpesatransaction_clerk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkuser',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
