# Generated by Django 5.2.6 on 2025-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clerkuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The full name of the freelancer.', max_length=255, null=True)),
                ('profession', models.CharField(help_text="The freelancer's primary profession or job title.", max_length=255)),
                ('bio', models.TextField(blank=True, help_text='A short biography or summary of the freelancer.')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture for the freelancer.', null=True, upload_to='freelancer_profiles/')),
                ('years_of_experience', models.IntegerField(default=0, help_text='Number of years of experience in their profession.')),
                ('skills', models.CharField(help_text="A comma-separated list of skills (e.g., 'React, Django, Python').", max_length=500)),
                ('availability', models.CharField(help_text="The freelancer's current availability (e.g., 'Full-time', 'Part-time').", max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('text', models.TextField(help_text='The full testimonial text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
