# Generated by Django 5.2.6 on 2025-09-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_freelancer_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='years_of_experience',
            field=models.CharField(help_text='Number of years of experience in their profession.', max_length=255),
        ),
        migrations.AlterField(
            model_name='gig',
            name='date',
            field=models.DateField(blank=True, help_text='The date the gig will take place.', null=True),
        ),
    ]
