# Generated by Django 5.2.6 on 2025-09-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_freelancer_years_of_experience_alter_gig_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='core.clerkuser'),
        ),
    ]
