# Generated by Django 5.2.6 on 2025-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gig_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='date',
        ),
        migrations.AlterField(
            model_name='gig',
            name='image',
            field=models.ImageField(blank=True, help_text='An image representing the gig.', null=True, upload_to='gig_images/'),
        ),
    ]
