# Generated by Django 5.2.6 on 2025-09-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_gig_contact_email_remove_gig_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='Cover Letter/Pitch')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_submitted', to='core.clerkuser')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.gig')),
            ],
            options={
                'verbose_name': 'Gig Application',
                'verbose_name_plural': 'Gig Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('gig', 'applicant')},
            },
        ),
    ]
