# Generated by Django 5.2.6 on 2025-10-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='core.freelancer'),
        ),
    ]
