# Generated by Django 5.2.6 on 2025-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_gig_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(default='No username', help_text='The full name of the freelancer.', max_length=255),
        ),
    ]
