# Generated by Django 5.2.6 on 2025-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_freelancer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
