# Generated by Django 5.2.7 on 2025-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_freelancer_clerk_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gig',
            name='clerk_user_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
