# Generated by Django 5.2.7 on 2025-10-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='clerk_user_id',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
