# Generated by Django 5.2.7 on 2025-10-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_gig_clerk_user_id_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='gig',
            name='clerk_user_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
